---

- name: Determine cloud provider
  when: CLOUD_PROVIDER is undefined
  block:
  - name: Check for env
    set_fact: 
      CLOUD_PROVIDER: "{{ lookup('env', 'BRS_CLOUD_PROVIDER') }}"
    when: lookup('env', 'BRS_CLOUD_PROVIDER') != ''
  - name: Asking for cloud provider
    ansible.builtin.pause:
      prompt: "Choose cloud provider; \n 1 - Hetzner"
      echo: yes
    register: output
    failed_when: output.user_input|int not in Providers.values()|map(attribute='id')|list
    when: Providers.values()|list|length > 1
  - set_fact:
      CLOUD_PROVIDER: "{{ Providers[output.user_input|int]['name'] }}"
    when: Providers.values()|list|length > 1
  - set_fact:
      CLOUD_PROVIDER: hetzner
    when: Providers.values()|list|length < 2
  rescue:
    - include_tasks: check-vars.yml

- name: Check CLOUD_API_KEY var
  when: CLOUD_API_KEY is undefined
  block:
  - name: Check for env
    set_fact: 
      CLOUD_API_KEY: "{{ lookup('env', 'BRS_CLOUD_API_KEY') }}"
    when: lookup('env', 'BRS_CLOUD_API_KEY') != ''
  - name: Asking for cloud provider API key
    ansible.builtin.pause:
      prompt: "Enter your provider API key"
      echo: yes
    register: output
  - set_fact:
      CLOUD_API_KEY: "{{ output.user_input }}"

- name: Check CLOUD_REGION var
  when: CLOUD_REGION is undefined
  block:
  - name: Check for env
    set_fact: 
      CLOUD_REGION: "{{ lookup('env', 'BRS_CLOUD_REGION') }}"
    when: lookup('env', 'CLOUD_REGION') != ''
  - name: Set CLOUD_REGION default value
    set_fact:
      CLOUD_REGION: 'eu'

- name: Check BITCOIN_USE_TESTNET var
  when: BITCOIN_USE_TESTNET is undefined
  block:
  - name: Check for env
    set_fact: 
      BITCOIN_USE_TESTNET: "{{ lookup('env', 'BRS_BITCOIN_USE_TESTNET') }}"
    when: lookup('env', 'BRS_BITCOIN_USE_TESTNET') != ''
  - name: Set BITCOIN_USE_TESTNET default value
    set_fact:
      BITCOIN_USE_TESTNET: 0
  
- name: Check BITCOIN_TXINDEX var
  when: BITCOIN_TXINDEX is undefined
  block:
  - name: Check for env
    set_fact: 
      BITCOIN_TXINDEX: "{{ lookup('env', 'BRS_BITCOIN_TXINDEX') }}"
    when: lookup('env', 'BRS_BITCOIN_TXINDEX') != ''
  - name: Set BITCOIN_TXINDEX default value
    set_fact:
      BITCOIN_TXINDEX: 1

- name: Check CLOUD_DISK_SIZE_GB var
  when: CLOUD_DISK_SIZE_GB is undefined
  block:
  - name: Check for env
    set_fact: 
      CLOUD_DISK_SIZE_GB: "{{ lookup('env', 'BRS_CLOUD_DISK_SIZE_GB') }}"
    when: lookup('env', 'BRS_CLOUD_DISK_SIZE_GB') != ''
  - name: Check CLOUD_DISK_SIZE_GB var
    set_fact:
      CLOUD_DISK_SIZE_GB: " {{ (BITCOIN_USE_TESTNET == 1) | ternary(50, (BITCOIN_TXINDEX == 1) | ternary (600, 500 )) }}"
- debug: msg="Automatically set cloud disk size to{{ CLOUD_DISK_SIZE_GB }}GB depending on configuration."

- name: Check BITCOIN_LOCAL_DATADIR var
  when: BITCOIN_LOCAL_DATADIR is undefined
  block:
  - name: Check for env
    set_fact: 
      BITCOIN_LOCAL_DATADIR: "{{ lookup('env', 'BRS_BITCOIN_LOCAL_DATADIR') }}"
    when: lookup('env', 'BRS_BITCOIN_LOCAL_DATADIR') != ''
  - name: Set BITCOIN_LOCAL_DATADIR default value
    set_fact:
      BITCOIN_LOCAL_DATADIR: "{{ playbook_dir }}/../"

- name: Check DEBUG var
  when: DEBUG is undefined
  block:
  - name: Check for env
    set_fact: 
      DEBUG: "{{ lookup('env', 'BRS_DEBUG') }}"
    when: lookup('env', 'BRS_DEBUG') != ''
  - name: Set DEBUG default value
    set_fact:
      DEBUG: 0
