# - name: "Check disk space"
#   shell: df --output=avail -B 1 "$PWD" | tail -n 1
#   register: output
#   failed_when: output|int < CLOUD_DISK_SIZE_GB * 1024 * 1024 * 1024

- debug: msg="Starting chain download"

- block:
  - name: Download chainstate
    ansible.posix.synchronize:
      mode: pull
      src: "{{ hostvars.cloud_vps.cloud_bitcoin_data_path }}/chainstate"
      dest: "{{ hostvars.localhost.BITCOIN_LOCAL_DATADIR }}"
      use_ssh_args: true
      compress: false
      checksum: false
      delay_updates: false
      archive: true
      rsync_opts:
        - "--log-file={{playbook_dir}}/../rsync.log"
        - "--delete"
        - "--inplace"
        - "--whole-file"
        - "--human-readable"
        - "-v"

  - name: Download blocks
    ansible.posix.synchronize:
      mode: pull
      src: "{{ hostvars.cloud_vps.cloud_bitcoin_data_path }}/blocks"
      dest: "{{ hostvars.localhost.BITCOIN_LOCAL_DATADIR }}"
      use_ssh_args: true
      compress: false
      checksum: false
      delay_updates: false
      archive: true
      rsync_opts:
        - "--log-file={{playbook_dir}}/../rsync.log"
        - "--delete"
        - "--inplace"
        - "--whole-file"
        - "--human-readable"
        - "-v"

  - name: Download indexes
    ansible.posix.synchronize:
      mode: pull
      src: "{{ hostvars.cloud_vps.cloud_bitcoin_data_path }}/indexes"
      dest: "{{ hostvars.localhost.BITCOIN_LOCAL_DATADIR }}"
      use_ssh_args: true
      compress: false
      checksum: false
      delay_updates: false
      archive: true
      rsync_opts:
        - "--log-file={{playbook_dir}}/../rsync.log"
        - "--delete"
        - "--inplace"
        - "--whole-file"
        - "--human-readable"
        - "-v"
  rescue:
    - include_tasks: download-chain.yml
  
- debug: msg="Download complete."
