
- debug: msg="Starting chain download"

- name: Download chain data
  ansible.posix.synchronize:
    mode: pull
    src: "{{ hostvars.cloud_vps.cloud_volume_path }}/bitcoin_data/"
    dest: "{{ hostvars.localhost.BITCOIN_LOCAL_DATADIR }}"
    use_ssh_args: true
    compress: false
    delay_updates: false
    rsync_opts:
      - "--log-file={{playbook_dir}}/../rsync.log"
      - "--size-only"
      - "-av"
      - "--append"
      - "--inplace"
      - "--partial"
      - "--no-compress"
      - "--human-readable"
      - "--info=progress2"
  register: rsync

- debug: msg="{{ rsync }}"
