- name: Prepare hosts
  hosts: localhost
  vars_files:
    - cloud/providers.yml
  tasks:
    - name: Verify dependencies
      include_tasks: local/tasks/verify-deps.yml
    - name: Check vars
      include_tasks: local/tasks/check-vars.yml
    - name: Provision VPS
      include_tasks: local/tasks/provision-vps.yml
- name: Sync bitcoin on cloud host
  hosts: cloud
  tasks:
    - name: Prepare cloud host
      include_tasks: "cloud/tasks/prepare-host.yml"
    - name: Wait for sync
      include_tasks: "cloud/tasks/check-sync-status.yml" 
    - name: Prepare download
      include_tasks: "cloud/tasks/prepare-download.yml"
- name: Download chain
  hosts: cloud_weak_cipher
  tasks:
    - name: Download chain
      include_tasks: "local/tasks/download-chain.yml"
- name: Clean up cloud
  hosts: localhost
  tasks:
    - include_tasks: "local/tasks/deprovision-vps.yml"
      