- name: Shutdown bitcoin
  shell: "bitcoin-cli stop"

- name: Wait for bitcoin to stop
  shell: "kill -0 $(cat {{ cloud_bitcoin_data_path }}/bitcoind.pid)"
  register: output
  until: output.rc != 0
  failed_when: output.rc == 0
  delay: 5
  retries: 300
